
#服务器端口
SERVER_PORT = 8088

#MYSQL
MYSQL_HOST = "127.0.0.1"
MYSQL_PORT = 3306
MYSQL_USER = "root"
MYSQL_PWD = "123456"
MYSQL_DB = "d_detectsys_sg"

#redis
REDIS_HOST = "127.0.0.1"
REDIS_PORT = 6379
REDIS_PASSWD = ""
EXPIRE_TIME = 3600
#MD5
MD5_SALT = "detectalarmsystem"

# CROPPED IMAGES
CROPPED_IMAGES_PATH = "./runs/cropped_images"
# MODEL PATH

# CAPTURE_WITH_EXE_PATH
CAPTURE_WITH_EXE_PATH = r"D:\x64\DetectAndDownload.exe"